# This file is made by MakerTim, a modded version of Sansko1337
# Last Changed 27-10-2015 21:25
buildfase:
  stage: build
  script:
# allow use of **
    - shopt -s globstar
# remove old build directory
    - rm -rf build
# create build and dist directory
    - mkdir build
    - mkdir -p ../dist
# set plugin version inside plugin.yml
    - "sed -e 's/^version.*$/version: '$(git rev-parse --short HEAD)';'$(git rev-parse HEAD)'/g' ./src/plugin.yml > ./src/plugin.yml.temp"
    - mv ./src/plugin.yml.temp ./src/plugin.yml
# compile all java files with as classpath everything inside libs directory
    - javac -cp $(find ./libs -regex '.*\.jar' -printf '%p:') -d ./build ./src/**/*.java
# copy all non java files to the build directory
    - (cd ./src; find . -type f ! -regex '.*\.java$' -exec cp '--parents' '{}' '../build' ';') 
# create a .jar file from everything inside the build directory AND put it in the ../dist directory
    - jar cvf ../dist/$(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g').jar -C ./build/ .
  only:
  - master
distributefase:
  stage: deploy
  script:
# Copy files to there locations
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g').jar
    - "echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server3/plugins/update"
    #- "echo $gitcipass|sudo -S chmod 777 /home/minecraft/multicraft/servers/server3/plugins/update/$1"
    #- echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server4/plugins/update
    #- echo $gitcipass|sudo -S chown "mc4:mc4" /home/minecraft/multicraft/servers/server4/plugins/update/&1
    #- echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server5/plugins/update
    #- echo $gitcipass|sudo -S chown "mc5:mc5" /home/minecraft/multicraft/servers/server5/plugins/update/&1
    #- echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server8/plugins/update
    #- echo $gitcipass|sudo -S chown "mc8:mc8" /home/minecraft/multicraft/servers/server8/plugins/update/&1
    #- echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server9/plugins/update
    #- echo $gitcipass|sudo -S chown "mc9:mc9" /home/minecraft/multicraft/servers/server9/plugins/update/&1
    #- echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server10/plugins/update
    #- echo $gitcipass|sudo -S chown "mc10:mc10" /home/minecraft/multicraft/servers/server10/plugins/update/&1
    #- echo $gitcipass|sudo -S cp ../dist/$1 /home/minecraft/multicraft/servers/server14/plugins/update
    #- echo $gitcipass|sudo -S chown "mc14:mc14" /home/minecraft/multicraft/servers/server14/plugins/update/&1
stages:
  - build
  - deploy