# This file is made by MakerTim, a modded version of Sansko1337
# Last Changed 03-03-2016 01:50
buildfase:
  stage: build
  script:
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g')
    - mvn clean install
    - curl -T target/$1.jar ftp://Deploy.3:$ftppass@localhost/plugins/update/
    - curl -T target/$1.jar ftp://Deploy.5:$ftppass@localhost/plugins/update/
    - curl -T target/$1.jar ftp://Deploy.9:$ftppass@localhost/plugins/update/
    - curl -T target/$1.jar ftp://Deploy.10:$ftppass@localhost/plugins/update/
    - curl -T target/$1.jar ftp://Deploy.14:$ftppass@localhost/plugins/update/
    - curl -T target/$1.jar ftp://Deploy.16:$ftppass@localhost/plugins/update/
    - curl -T target/$1.jar ftp://Deploy.17:$ftppass@localhost/plugins/update/
stages:
  - build
