name: HUB_Essemtials
main: nl.MakerTim.HubEssentials.BukkitStarter
version: 1.CI_BUILD_ID CI_BUILD_REF

commands:
  hub:
    description: Go to the hub server
    usage: /hub  to go to the hub
  git:
    description: Git checker - are you up to date?
    usage: /git to see if everything is up to date
  dev:
    description: DEVMODE = kick everyone now!
    usage: /dev
  report:
    description: Report to all admins a issue
    usage: /report <issue>
    aliases: [r, rep, repo, abuse, meld]
  admin:
    description: Admin Chat
    usage: /Admin <chat>
    aliases: [a, intern, internal, internally]
  update:
    description: Do the most horrible thing
  plr:
    description: Do the most horrible thing
    usage: /plr pluginname
    aliases: [pluginreload, plreload, pluginr] 
  tp:
    description: Teleport to that...
    usage: /tp <Who> [Player]
    aliases: [teleport]
  gm:
    description: Change gamemode
    usage: /gm [gamemode] <Who>
    aliases: [gamemode]
  gm0:
    description: Change gamemode to survival
    usage: /gm0 <Who>
    aliases: [gamemodesurvival, gamemodes]
  gm1:
    description: Change gamemode to creative
    usage: /gm1 <Who>
    aliases: [gamemodecreative, gamemodec]
  gm2:
    description: Change gamemode to adventure
    usage: /gm2 <Who>
    aliases: [gamemodeadventure, gamemodea]
  speed:
    description: Set your speed
    usage: /speed [Speed] <what> <Who>
    aliases: [speeds]
  msg:
    description: Whispering sounds
    usage: /msg [Who] [Message]
    aliases: [m, t, whisper, tell]
