name: HUB_Essemtials
main: nl.MakerTim.HubEssentials.BukkitStarter
version: 1.CI_BUILD_ID CI_BUILD_REF

commands:
  hub:
    description: Go to the hub server
    usage: /hub  to go to the hub
  git:
    description: Git checker - are you up to date?
    usage: /git to see if everything is up to date
  dev:
    description: DEVMODE = kick everyone now!
    usage: /dev
  report:
    description: Report to all admins a issue
    usage: /report <issue>
    aliases: [r, rep, repo, abuse, meld]
  admin:
    description: Admin Chat
    usage: /Admin <chat>
    aliases: [a, intern, internal, internally]
  update:
    description: Do the most horrible thing
  plr:
    description: Do the most horrible thing
    usage: /plr pluginname
    aliases: [pluginreload, plreload, pluginr]
    